In [88]:
# Rappresentiamo la Scacchiera come un array bidimensionale 8x8 chimato `board`:
# Importiamo le librerie standard di python che ci serviranno in questo progetto:
import random
import collections

# Le librerie dei framework specifici:
import matplotlib.pyplot as plt # Motore grafico di python per realizzare diagrammi e fuznoni
import numpy as np # Libreria che gestisce ad altissima efficienza gli array
import seaborn as sns # Libreria che usa il motore grafico di MatplotLib con funzionalita' grafiche avanzate

Rappresentiamo la scacchiera con un array bidimensionale 8x8 riempito di Zeri. Il cavallo si muove nella scacchiera partendo da una casella che verra' marcata col numero 1. Teniamo traccia degli spostamenti del cavallo incrementando di 1 ogni passaggio, ottenendo dunque un array di questo tipo: 
''' array([[ 0., 0., 0., 0., 0., 0., 0., 0.], [ 0., 0., 0., 0., 0., 0., 0., 0.], [ 0., 0., 3., 0., 0., 0., 0., 0.], [ 4., 0., 8., 0., 2., 17., 0., 0.], [ 7., 0., 5., 0., 0., 0., 13., 0.], [ 0., 9., 0., 1., 18., 11., 16., 0.], [ 0., 6., 0., 10., 0., 14., 0., 12.], [ 0., 0., 0., 0., 0., 19., 0., 15.]]) '''
Da questo array si possono vedere tutti i salti che ha fatto il cavallo ha fatto 19 salti (sui 64 possibili) prima di non riuscire piu' a muoversi su caselle mai toccate.

In [89]:
# Scriviamo una funzione che inizializzi il gioco, creando una "board" e posizionando il cavallo nella sua posizione iniziale.
# Consideriamo la possibilita' di far partire il cavallo da una delle sue posizioni "standard"
# o da una posizione casuale nella scacchiera:

def initialize_game(horse_default_position=True):

    board = np.zeros((8,8))
    positions = [(0,1), (0,6), (7,1), (7,6)]
    start_position = random.choice(positions)

    board[start_position] = 1

    # print(board)
    return board

In [90]:
my_board = initialize_game()
my_board

array([[0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [91]:
# Scrviamo una funzione che legge una board e restituisce:
# - il numero di mosse raggunto dal cavallo
# - una tupla con la posizione attuale, orizzontale e verticale
def get_horse_current_position(board):

    current_move_number = board.max()
    current_h, current_v = np.unravel_index(my_board.argmax(),(8,8))


    # return current_move_number, (current_h, current_v)
    return current_move_number, (current_h, current_v)

In [92]:
get_horse_current_position(my_board)

(1.0, (0, 6))

In [93]:
# Scriviamo una funzione che legge una board e restituisce una lista delle possibili mosse disponibili
def get_available_moves(board):

    possible_moves = [(2,1),
                      (2,-1),
                      (-2,1),
                      (-2,-1),
                      (1,2),
                      (1,-2),
                      (-1,2),
                      (-1,-2)]
    
    _, current_horse_position = get_horse_current_position(board)
    h_pos, v_pos = current_horse_position

    available_moves = []

    for move in possible_moves:
        h_move, v_move = move
        new_h_pos = h_pos + h_move
        new_v_pos = v_pos + v_move
        if 0<=new_h_pos<=7:
            if 0<=new_v_pos<=7:
                if board[(new_h_pos, new_v_pos)] == 0:
                    available_moves.append((new_h_pos, new_v_pos))

    
    # return available_moves
    return available_moves


In [94]:
get_available_moves(my_board)

[(2, 7), (2, 5), (1, 4)]

In [95]:
# Scriviamo una funzione che date le mosse a disposizione, ne sceglie casualmente una e la restituisce
def random_move(available_moves):

    return random.choice(available_moves)
    # return a_random_move

In [96]:

# Scriviamo una funzione che legge una board e fa fare al cavallo una mossa scegliendo tra le disponibili casualmente

def move_horse(board):

    current_move, _ = get_horse_current_position(board)
    next_move_count = current_move + 1

    available_moves = get_available_moves(board)
    if len(available_moves) == 0:
        return("Game over")
    next_move = random_move(available_moves)
    board[next_move] = next_move_count

    # return board
    return board

In [97]:
move_horse(my_board)

[[0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [98]:

# Scriviamo una funzione che gioca una partita completa sino a che il cavallo non puo' piu' muoversi
# A fine partita, se il parametro "verbose" e' impostato su true, stampa a video la board.
# Restituisce la board
def play_one_game(verbose = False, horse_default_start_position = True):

    board = initialize_game()
    # return board
    pass

# Scriviamo una funzione che gioca n partite e restituisce un po' di statistiche:
# - Numero partite vinte o miglior partita,
# - Board completate o miglior Board
# - Punteggio raggiunto in media e mediana,
# - Frequenza di occupazione di alcune caselle nella board
# - vvee
def play_multiple_games(n= 10, verbose = False, horse_default_start_position = True):

    # return statistics
    pass